export const sampleIAMData = [
  {
    id: 1,
    username: "john.doe",
    email: "john.doe@company.com",
    role: "Administrator",
    department: "IT Security",
    lastLogin: "2024-05-20",
    lastPasswordChange: "2023-12-15",
    mfaEnabled: false,
    privilegedAccess: true,
    accountActive: true,
    daysInactive: 0,
  },
  {
    id: 2,
    username: "jane.smith",
    email: "jane.smith@company.com",
    role: "Manager",
    department: "Finance",
    lastLogin: "2024-05-25",
    lastPasswordChange: "2024-01-10",
    mfaEnabled: true,
    privilegedAccess: false,
    accountActive: true,
    daysInactive: 0,
  },
  {
    id: 3,
    username: "bob.wilson",
    email: "bob.wilson@company.com",
    role: "User",
    department: "HR",
    lastLogin: "2024-05-12",
    lastPasswordChange: "2023-11-20",
    mfaEnabled: false,
    privilegedAccess: false,
    accountActive: true,
    daysInactive: 13,
  },
  {
    id: 4,
    username: "alice.brown",
    email: "alice.brown@company.com",
    role: "Administrator",
    department: "IT Operations",
    lastLogin: "2024-01-05",
    lastPasswordChange: "2023-08-30",
    mfaEnabled: false,
    privilegedAccess: true,
    accountActive: true,
    daysInactive: 141,
  },
  {
    id: 5,
    username: "charlie.davis",
    email: "charlie.davis@company.com",
    role: "User",
    department: "Marketing",
    lastLogin: "2024-03-10",
    lastPasswordChange: "2024-02-01",
    mfaEnabled: true,
    privilegedAccess: false,
    accountActive: false,
    daysInactive: 76,
  },
];